// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetRows(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRows'](arg1, arg2, arg3);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadCSV(arg1) {
  return window['go']['main']['App']['LoadCSV'](arg1);
}

export function OpenCSV() {
  return window['go']['main']['App']['OpenCSV']();
}

export function SaveCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCSV'](arg1, arg2, arg3);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
